service: aws-lambda-dynamodb-crud
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  iamRoleStatements: # Todo lo que esta aqui adentro es para otorgarle permisos al proyecto para modificar las tablas descritas en "Resource"
    - Effect: Allow # Otorga el permiso / Gives permission to DynamoDB tables in a specific region
      Action: # Todos los permisos
        - dynamodb:*
      Resource: # Tablas afectadas
        - arn:aws:dynamodb:us-west-1:493103141670:table/Tasks

functions:
  createTask:
    handler: src/tasks/create.createTask
    events:
      - httpApi:
          path: /tasks/create
          method: post
  getAllTasks:
    handler: src/tasks/getAll.getAllTasks
    events:
      - httpApi:
          path: /tasks/getAll
          method: get
  getTaskById:
    handler: src/tasks/getById.getTaskById
    events:
      - httpApi:
          path: /tasks/getById/{id}
          method: get
  updateTask:
    handler: src/tasks/update.updateTask
    events:
      - httpApi:
          path: /tasks/update/{id}
          method: put

resources:
  Resources:
    Tasks: # Nombre del recurso
      Type: AWS::DynamoDB::Table # Tipo de recurso -> Tabla
      Properties:
        TableName: Tasks # Nombre de la tabla
        BillingMode: PAY_PER_REQUEST # Forma de pago -> Pago por peticion
        AttributeDefinitions: # Definicion de una columna
          - AttributeName: id # Nombre de la columna
            AttributeType: S # Tipo de valor -> S -> String
        KeySchema: # Definicion de las caracteristicas de la columna
          - AttributeName: id
            KeyType: HASH # La columna "id" es de tipo HASH
